# Generated by Django 4.2.7 on 2023-12-05 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
